### PR TITLE
[WIP] Add separators

### PR DESCRIPTION
**Pull request by Jackymancs4**
Hello @CanisLupus 
I really love you extension. Here it is a little feature I was missing (and was already issued #32 ).

| Before | After |
| -- | -- |
| before - final | after - final | 

Since the new element is a ```sss``` type engine, it works out of the box exactly as ```Copy to Clipboard```

settings - final

I'm definetely not convinced about the esthetic, but that's easy to change since the separator is a div with a CSS stylesheet applied to it.
Also the icon that appears in the settings page doesn't feel very good.

Tests and screeshots taken on Firefox 59.0.1 on MacOS 10.13.3

### CODE REVIEW

**Comment by CanisLupus** [comment]
Hey there Giacomo!

Did you know you are awesome? Thank you very much for your work! :D I haven't had time to look at your additions in detail (just a glance) but the result sure looks nice! I'll take a look and comment as soon as I can.

I also probably should add better code comments for other people to understand SSS and contribute if they wish. :)

Again, thanks!

Cheers,
Daniel

**Comment by Jackymancs4** [comment]
Thank you for the kind words, and for your awesome addon, of course xD

> I also probably should add better code comments for other people to understand SSS and contribute if they wish. :)

Comments and docs are always a big thumb up, but I really enjoyed looking into your codebase! It's been incredibly easy to read and understand.. So, great work, really 👍 

This morning I worked on two (actually three) little 'fixes' to have the SSS of my dreams, would you mind taking a look at some other PR?

**Comment by CanisLupus** [comment]
You are welcome, and thanks! :)

I'm happy that you could find your way around my code! I'm not a web/JS programmer and I left large portions of uncommented code, so that's great. I've wrote down a note to add a few comments here and there later. ;)

I've merged your code into the SSS repo and added a commit to consolidate the changes. Besides a few naming and formatting changes (I also moved some of my code to functions to better accomodate the new separator type), I added a delete button for the separators.

Also, I agree with the padding changes to the options page! It's much more readable now. :) However -- and I hope you don't mind -- I slightly reduced the values from 10px to 8px, to not use up so much vertical space.

Still have to decide about the separator icon too. I would prefer to unify the icon in the settings page and popup to both use either CSS or the image. I'm leaning toward CSS, since someone will likely request options to change the separator. ;)

Now, about your fixes, sure I can take a look! I really appreciate your contribution. What I can't promise is how much time I'll take hehe.

Cheers!
Daniel

**Comment by Jackymancs4** [comment]
Awesome!

> I'm not a web/JS programmer

I am and I must admit that I'm really impressed by your work 🥇 

> Also, I agree with the padding changes to the options page! It's much more readable now. :) However -- and I hope you don't mind -- I slightly reduced the values from 10px to 8px, to not use up so much vertical space.

That commit splipped in the wrong branch, and I'm sorry it's not been very polite! It was one of the little changes I wanted to propose afterwards.. 
Also, I think you are right in lowering it a bit.

> I'm leaning toward CSS

Definetely a good idea for the sake of consistency.

> I added a delete button for the separators.

I can't believe I forgot to add a delete button!

**Comment by CanisLupus** [comment]
Thank you for the medal! hehe I mostly did what I thought made more sense. The thing that stumbles me the most in organizing things is the way scripts have to communicate in WebExtensions, and not having compile-time checks (maybe TypeScript would help, but I never tried it, nor do I know if it plays well with WebExtension development).

No problem! I was also not sure if I should try committing my changes to your branch (can I do that?), since it was related, or just update things on my side directly. I ended up doing the latter to avoid confusion, but do you know if that's the usual way? I'm not at all experienced with handling pull requests. :)

**Comment by Jackymancs4** [comment]
> maybe TypeScript 
I always wanted to try it, never had time 😅 

> can I do that?
Indeed you can, it happen quite often in big codebases repo to have PR on PR on PR (PRception), but it is definetely worth trying to avoid it if it's not mandatory in the case.

**Comment by CanisLupus** [comment]
I see. It sounded a bit cumbersome. xD Thanks for the explanation.

**Pull request merged**
